### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by zappen999** [bambora/checkout-woocommerce#11]
```Warning: Division by zero in /var/www/html/wp-content/plugins/woocommerce-gateway-bambora-v1.4.2/woocommerce-gateway-bambora.php on line 416```

Is this module stable enough to use in production?

Thanks.

**Comment by sorenla** [comment]
Hello zappen999

Yes, this module has been used in production for a while now. The previous release (1.4.0) introduced some refactoring which unfortunately introduced the two issues you have pointed out. 

We appreciate the feedback, thanks!

I have published a fix which resolves this possible division by zero error: [Release v1.4.3](https://github.com/bambora/checkout-woocommerce/releases/tag/v1.4.3)
