### ISSUE TITLE
Transaction ID is not saved

### ISSUE THREAD

**Issue by jonathan-dejong** [bambora/checkout-woocommerce#13]
Hi,
So I noticed when installing this plugin that the meta key (and value) "Transaction ID" aren't saved to the order.

This results in absolutely no connection to the payment in Bambora merchant view from the WooCommerce backend. It just ends up with "No transaction ID" in the meta box. 

I tried adding it manually to an order and then everything popped up. 
I suspect this issue is due to the new CRUD classes in WooCommerce 3.0+. 

Not sure how much of a priority this is for you guys but the plugin is essentially half useless right now (in my opinion).

**Comment by AllanWLie** [comment]
Hi @jonathan-dejong ,

We are currently working on a new release correcting this issue.

**Comment by jonathan-dejong** [comment]
Hi @AllanWLie 

Do you have any ETA? I work against the clock here and am currently trying to fix it myself.
So far I've figured out that the API action that's in charge of checking the callback does not fire:
`add_action( 'woocommerce_api_' . strtolower( get_class() ), array( $this, 'check_callback' ) );`
on line ~117 in bambora-online-checkout.php. 

It looks correct tho, and testing it with `add_action( 'woocommerce_api_bambora_online_checkout', array( $this, 'check_callback' ) );` does not work either. 

I'm quite certain it's the correct type of hook to use. Looking at other bambora plugins they're using the same one.

**Comment by AllanWLie** [comment]
The release is out now fixing your issue: https://github.com/bambora/checkout-woocommerce/releases/latest

The release will be available in the WordPress marked in 15min.

**Comment by jonathan-dejong** [comment]
Hi @AllanWLie 

Unfortunately that did not fix it.

The function `process_callback` is never called. 
I'm using your latest version now along with latest version of WC. 
Tried placing an error_log at the very beginning of the function and it never occurs.

**Comment by AllanWLie** [comment]
@jonathan-dejong 

We are running WooCommerce 3.1.2 and we can not reproduce your issue.

Please submit a support ticket at support@bambora.com so that we can find the data we are sending to your shop. 

Please provide all releavant informations like, Merchant number, Woocommerce version and if you got it a transaction id.

**Comment by jonathan-dejong** [comment]
Strange.. 

Is it possible to bypass the regular queue? I've been talking to you on your support email a while but there's always at least 2 days waiting for me which I don't have now.. :/

**Comment by AllanWLie** [comment]
I am sorry to hear that but I can not do anything unless we have your informations. Which you should not post in this public forum.

It seem like you are not getting the Callback from our server, this might be due to some other plugin blocking it. Try to disable your other plugins, and do a test transaction.

**Comment by jonathan-dejong** [comment]
Yeah of course I wont post anything like that :) 

I've tried disabling all other plugins except ACF, WooCommerce and Bambora. Still not working. 
I looked at the requests that are made during the checkout but everything looks fine as far as I can tell. 

Just updated to 3.0.5 too but alas.. same issue :/ 

Can I give you the merchant number here so you can look at the account on your end? Shouldn't be any issues with it being public no?

**Comment by AllanWLie** [comment]
You could try to post your registered company name and / or domain.
I can not garanti that I can fix it. So I would like before recommend that you add a support ticket.

**Comment by jonathan-dejong** [comment]
I will create a support ticket as well then. 
The company is I Love Pizza. Domain is ilovepizza.se

**Comment by jonathan-dejong** [comment]
Hey,

yep thats correct. It's my local dev environment.. 
So that's why it wont work then.. hmm bummer.

If I send you a staging domain (can't type it out here) can you add it as an accepted domain too? So I can keep working on it there then

**Comment by AllanWLie** [comment]
Hi @jonathan-dejong 
Our support will contact you regarding the domain change. 

Have a nice day.

Best regards
Allan
