### ISSUE TITLE
Here's swedish translation

### ISSUE THREAD

**Issue by jonathan-dejong** [bambora/checkout-woocommerce#16]
Hi,

In case you want it. Swedish translation of all strings (including the ones I fixed in the PR)
[bambora_sv_SE.zip](https://github.com/bambora/checkout-woocommerce/files/1320788/bambora_sv_SE.zip)

**Comment by AllanWLie** [comment]
Hi @jonathan-dejong 

Nice work, with your translations and your pull request. Based on the issues a few days ago we had to make a quick release, patching the critical bugs. We are now working on some more improvements, and we will add you pull request (so you get the credit).

Regarding the language pack. In the new release we are working on, there might be some language changes, so you might need to update your Swedish translations. I propose that when the release is done, you do a new pull request adding the Swedish translations (and also getting the credit for it). 

Thank you for your contribution to our module.

Best regards
Allan

**Comment by jonathan-dejong** [comment]
Hi @AllanWLie 

Thanks. Alright I will update my translation when that's done.
In regards to you working on the plugin.. I would like to propose a change which would greatly help my situation.

In my current project the client are supposed to use Bambora Checkout with multiple merchants.
The customer selects which merchant they want to purchase from and based on that I need to change all the API values for the checkout. 
In the frontend I do this by having a session variable set with the restaurants post ID. From that I then fetch the specific merchant API information which is stored as post meta. 

I've attempted solving this by just wrapping all your `$this->merchantID = …` etc in apply_filters so that I could hook into that and change it. This works to 99%.. 

The problem is that these values are set in __construct, thus they are usually set before I can access my $_SESSION variable and find out what the replacing values should be. As I said tho, this works *almost* all the way. The checkout works, the payment is sent to your system BUT the callback fails (more specifically the md5key hash check)..

My theory is that if you put these values in setters and getters which are called upon whenever the values is needed and wrap these in apply_filters it should work all the way.. I've not tried it yet tho as I've attempted to solve it as is. 

Your thoughts?

**Comment by AllanWLie** [comment]
@jonathan-dejong ,

One thought could be to append your store id to the Callback url  (https://github.com/bambora/checkout-woocommerce/blob/master/bambora-online-checkout/bambora-online-checkout.php#L532) before sending it to us. Then when we send you the callback you will have the store id and based on that you could call your hook. before before our "valid_bambora_callback" hook is called. (https://github.com/bambora/checkout-woocommerce/blob/master/bambora-online-checkout/bambora-online-checkout.php#L683) and (https://github.com/bambora/checkout-woocommerce/blob/master/bambora-online-checkout/bambora-online-checkout.php#L117)

**Comment by jonathan-dejong** [comment]
Hey @AllanWLie 

Finally had time to look this over again. 
Thank you for that tip! 

I think I've actually managed to pull this off (including having the merchant change in admin depending on the orders merchant). I also managed to make it work with just a single apply_filters in your plugin :) 

I've changed this line https://github.com/bambora/checkout-woocommerce/blob/master/bambora-online-checkout/bambora-online-checkout.php#L532

to this:

`
$callback->url = apply_filters( 'bambora_callback_url', $this->fix_url( add_query_arg( array(
                'wooorderid' => $order_id,
                'wc-api' => 'Bambora_Online_Checkout',
            ), $this->get_return_url( $order ) ) ) );
`

Essentially I've added the bambora_callback_url filter hook to the url and also cleaned it up so it does not run add_query_arg twice (not needed). 

If you could find it in your heart to add that to the official plugin I'd be so happy!

If you want to have a look at how here's the code (little bit cleaned up from irrelevant things).
https://gist.github.com/jonathan-dejong/e1727e52c7360609b211842ca2145973

**Comment by AllanWLie** [comment]
Hi @jonathan-dejong 

Nice work. The new release we are working on will include a very large refactoring of the module (one of the changes is how callbacks and accept urls are handled including the usage of filters).

At the moment I can not give you a hard deadline, but it will come in the near future.

**Comment by jonathan-dejong** [comment]
@AllanWLie that's equal parts exciting and terrifying.. :D
So will that still contain some way for me to do the same thing as above? Perhaps even in a cleaner and more performant matter ;)

**Comment by AllanWLie** [comment]
Hi @jonathan-dejong,

We are almost done with the major update of our module. The main updates is how the module handles subscriptions. 

My question to you is. Do you use subscriptions and do you want to test our module ?

Your help is appreciated :)

**Comment by jonathan-dejong** [comment]
Hi @AllanWLie 

Unfortunately I don't have any projects which uses Subscription based payments with Bambora.. 
So I likely wont be useful in testing I'm afraid.. But it's nice to hear that you're making good progress!

**Comment by AllanWLie** [comment]
Hi @jonathan-dejong 
We have now released the new and improved module. Please notice that the release is a Beta release and it might not be stable. Please make a backup of your shop before installing this plugin. 

Regarding translations: Since this is a beta release there might still be some changes to the module, but the texts should be in place for translation. So if you are still up to it, then it could be nice if you would translate the texts to Swedish :) 

Thank you.

**Best regards** 
Allan

**Comment by jonathan-dejong** [comment]
Hi @AllanWLie 
Nice! I'll be sure to PR a translation for you :) 
In terms of my "workaround" to make it work for our project with multiple merchants, how much change is it to apply? 
Just having  a quick look it seems you've added some useful filters :)

**Comment by AllanWLie** [comment]
@jonathan-dejong 
Nice. 
Think that the example you did would do the trick for you. You could apply it to the bambora-online-checkout.php file. The only flaw in this plan is that your changes will get overwritten when we do a new release. 

You could also keep your code in a separate file outside our module, and the include it ( include('yourfilepath/yourfile.php') ) and in the constructor of our module create a new instance of your class. Then you will only need to apply a few lines of code to our module every time it gets updated.

**Comment by jonathan-dejong** [comment]
in my current solution I've only had to add a single line of code to your files (or rather wrap a value in a filter). 
From the looks of it you've added a filter in the new version? 
https://github.com/bambora/checkout-woocommerce/blob/v4.0.0-beta/bambora-online-checkout/bambora-online-checkout.php

**Comment by AllanWLie** [comment]
Okay.

I could add this to the module. Would this help you ? 

`/**
         * Initilize Bambora Online Checkout Settings
         */
        public function init_bambora_checkout_settings()
        {
            $enabled = array_key_exists( 'enabled', $this->settings ) ? $this->settings['enabled'] : 'yes';
            $title = array_key_exists( 'title', $this->settings ) ? $this->settings['title'] : 'Bambora Online Checkout';
            $description = array_key_exists( 'description', $this->settings ) ? $this->settings['description'] : 'Pay using Bambora Online Checkout';
            $merchant = array_key_exists( 'merchant', $this->settings ) ? $this->settings['merchant'] : '';
            $access_token = array_key_exists( 'accesstoken', $this->settings ) ? $this->settings['accesstoken'] : '';
            $secret_token = array_key_exists( 'secrettoken', $this->settings ) ? $this->settings['secrettoken'] : '';
            $payment_window_id = array_key_exists( 'paymentwindowid', $this->settings ) ? $this->settings['paymentwindowid'] : 1;
            $window_state = array_key_exists( 'windowstate', $this->settings ) ? $this->settings['windowstate'] : 2;
            $instant_capture = array_key_exists( 'instantcapture', $this->settings ) ? $this->settings['instantcapture'] :  'no';
            $immediate_redirect_to_accept = array_key_exists( 'immediateredirecttoaccept', $this->settings ) ? $this->settings['immediateredirecttoaccept'] :  'no';
            $add_surcharge = array_key_exists( 'addsurchargetoshipment', $this->settings ) ? $this->settings['addsurchargetoshipment'] :  'no';
            $md5_key = array_key_exists( 'md5key', $this->settings ) ? $this->settings['md5key'] : '';
            $rounding_mode = array_key_exists( 'roundingmode', $this->settings ) ? $this->settings['roundingmode'] : Bambora_Online_Checkout_Currency::ROUND_DEFAULT;

            // Define user set variables!
            $this->enabled = apply_filters( 'bambora_online_checkout_enabled', $enabled );
            $this->title = apply_filters( 'bambora_online_checkout_title', $title );
            $this->description = apply_filters( 'bambora_online_checkout_description', $description );
            $this->merchant = apply_filters( 'bambora_online_checkout_merchant', $merchant );
            $this->accesstoken = apply_filters( 'bambora_online_checkout_access_token', $access_token );
            $this->secrettoken = apply_filters( 'bambora_online_checkout_secret_token', $secret_token );
            $this->paymentwindowid = apply_filters( 'bambora_online_checkout_payment_window_id', $payment_window_id );
            $this->windowstate = apply_filters( 'bambora_online_checkout_window_state', $window_state );
            $this->instantcapture = apply_filters( 'bambora_online_checkout_instant_capture', $instant_capture );
            $this->immediateredirecttoaccept = apply_filters( 'bambora_online_checkout_immediate_redirect_to_accept', $immediate_redirect_to_accept );
            $this->addsurchargetoshipment = apply_filters( 'bambora_online_checkout_add_surcharge', $add_surcharge );
            $this->md5key = apply_filters( 'bambora_online_checkout_md5_key', $md5_key );
            $this->roundingmode = apply_filters( 'bambora_online_checkout_rounding_mode', $rounding_mode );
        }`

**Comment by AllanWLie** [comment]
Come to think of it. It would be much more clean to apply a filter to the init_bambora_checkout_settings() function like this. 

apply_filters('bambora_online_checkout_init_settings', $this->init_bambora_checkout_settings() );

**Comment by AllanWLie** [comment]
Then you could listen for the filter and change the settings according to your shop.

**Comment by AllanWLie** [comment]
Hi @jonathan-dejong 

Not to rush you, but did you do the Swedish translations for the new release :)

Have a nice day.

**Comment by jonathan-dejong** [comment]
Hey @AllanWLie 

I've sent you a PR now with Swedish translations : )
We're likely going to use Bambora for another project where there might be multiple merchants involved again so it'll be exciting to make it work with this new and improved version :)

**Comment by AllanWLie** [comment]
Hey @jonathan-dejong 
Thank you for the translations. I have added them to the module and created a new release with them included.

Hope all goes well with your multiple merchant implementation.

Have a great day.

-Allan

**Comment by jonathan-dejong** [comment]
Hey @AllanWLie 

It seems you've removed the filters previously added in order to be able to hook into and modify the settings values? 

I'm looking to setup a new plugin which should do basically the same as the above (multiple merchants) but looking at your latest released plugin version there's not a single filter?

**Comment by AllanWLie** [comment]
Hi @jonathan-dejong 

We did only add a filter for the callback url. 
https://github.com/bambora/checkout-woocommerce/blob/master/bambora-online-checkout/bambora-online-checkout.php#L659

**Comment by jonathan-dejong** [comment]
hi @AllanWLie 

May I ask why? Without the filters for the settings there is no way for me to use your plugin for multiple merchants as discussed earlier.. :)

**Comment by AllanWLie** [comment]
You wrote this, and we added the filter to the Callback url as you requested.
> Finally had time to look this over again.
> Thank you for that tip!
> 
> I think I've actually managed to pull this off (including having the merchant change in admin depending on the orders merchant). I also managed to make it work with just a single apply_filters in your plugin :)
> 
> I've changed this line https://github.com/bambora/checkout-woocommerce/blob/master/bambora-online-checkout/bambora-online-checkout.php#L532
> 
> to this:
> 
> $callback->url = apply_filters( 'bambora_callback_url', $this->fix_url( add_query_arg( array( 'wooorderid' => $order_id, 'wc-api' => 'Bambora_Online_Checkout', ), $this->get_return_url( $order ) ) ) );
> 
> Essentially I've added the bambora_callback_url filter hook to the url and also cleaned it up so it does not run add_query_arg twice (not needed).
> 
> If you could find it in your heart to add that to the official plugin I'd be so happy!

**Comment by jonathan-dejong** [comment]
Ah lol .. I guess I was kind of unclear. 
I made it work just fine (and it might still with the new version) however it's not the prettiest of solution. So I'd still want the filters because it'd make it much more streamlined and easier to read (my code involves dynamically creating hooks based on other hooks for example). 

So while it works as is, it'd been neat if there were filters to make is simpler :)

**Comment by AllanWLie** [comment]
Hehe,
I have added a task to our roadmap, but at this point I do not know when I will get to implementing it. 

You can always make a pull request (If you do, make it as simple as possible so that other users do not get affected by the changes :) )

Have a nice day.

-Allan
