### ISSUE TITLE
Save cards for future use?

### ISSUE THREAD

**Issue by goranefbl** [bambora/checkout-woocommerce#18]
I am looking at the payment profiles docs https://dev.na.bambora.com/docs/guides/payment_profiles/ and wondering is it possible to save customer cards for later use through this API?

Also is this EU only? I see that endpoints are connecting to the eu api. And video in documentation has totally different admin UI than what we have in NA.

**Comment by AllanWLie** [comment]
Hi @goranefbl 
This module is for the Bambora Online Checkout payment system which targets the the European market.

For questions about the North American API please go to this site: https://help.na.bambora.com/hc/en-us and submit a request

Have a good day

Best regards
Allan
