### ISSUE TITLE
CURLOPT_SSL_VERIFYPEER set to false in REST client

### ISSUE THREAD

**Issue by elsand** [bambora/checkout-woocommerce#2]
Setting CURLOPT_SSL_VERIFYPEER to false disable certificate checks of the API endpoint, making MITM attacks possible. Please consider bundling https://curl.haxx.se/ca/cacert.pem or a similar CA certificate store, and refer to it by setting CURLOPT_CAINFO, which makes it possible for cURL to verify peer certificates.

**Comment by AllanWLie** [comment]
Thank you for reporting this issue. We will look into it and consider it for the next release. In the meantime feel free to make a pull request and implement the issues.

**Comment by sorenla** [comment]
Fixed in version 1.2.8
