### ISSUE TITLE
WooCommerce Subscriptions - Payment failing on renewal

### ISSUE THREAD

**Issue by syntaxerror** [bambora/checkout-woocommerce#21]
Seems like there are some issues with the WooCommerce Subsriptions support, as payments are failing on renewal.

When adding the initial subscription order all seems fine in the webshop, and the payment will be a success on both manual and direct capture.

But when looking at the subscription in 'Old Back Office' (old-merchant) there is noted 'Warning No Access' on the left bellow 'AUTHORIZE AMOUNT', and there is no transactions listed.

Then when the renewal happens the new order is added in the webshop, but the payment will fail with a 'User not authorised' error message.

Confirmed on a clean WP test site created just to test this. Only added WooCommerce, Bambora and WooCommerce Subscriptions.

Wordpress 5.0.3
WooCommerce 3.5.4
WooCommerce Subscriptions 2.4.7
Bambora Checkout Module 4.2.0
PHP 7.2.14

Attaching some images with id's etc. hidden, if you need the merchant id etc. to check your logs just let me know and I can mail them to you. I'm also happy to give you access to the test site if needed.
![bambora-edit-order-subscription-renewal](https://user-images.githubusercontent.com/858132/52467929-c8c23800-2b8f-11e9-82ea-ea4e132e1cf5.png)
![bambora-edit-order-subscription-start](https://user-images.githubusercontent.com/858132/52467933-cc55bf00-2b8f-11e9-8182-b97c4aff8c84.png)
![bambora-edit-subscription](https://user-images.githubusercontent.com/858132/52467935-cf50af80-2b8f-11e9-9031-1713cbd168f3.png)
![bambora-merchant-subscription-first-payment](https://user-images.githubusercontent.com/858132/52467937-d1b30980-2b8f-11e9-98a5-8ef2ecb3b6f6.png)
![bambora-merchant-subscription-new](https://user-images.githubusercontent.com/858132/52468089-4be38e00-2b90-11e9-9783-ea76ba9e894f.png)
![bambora-oldmerchant-subscription-new](https://user-images.githubusercontent.com/858132/52468091-4dad5180-2b90-11e9-865d-479a7badcc1d.png)
![bambora-subscriptions-error-log](https://user-images.githubusercontent.com/858132/52468093-4ede7e80-2b90-11e9-834c-170bcd110124.png)

**Comment by AllanWLie** [comment]
@syntaxerror 

Please contact support@bambora.com

-Allan

**Comment by syntaxerror** [comment]
The client have contacted them several times without receiving any help.

But I also wonder, because you tell me to do this, do you consider it to be account related, and not a bug in the module?

**Comment by AllanWLie** [comment]
All merchant related support should go through our support channel. 
Support on Github is only happening from time to time and there is no guarantee that we will answer here.

And to answer your question. Yes I think it is a merchant specifik issue, since I am unable to reproduce the issue. 

So create a support ticket with all the info and include info about the merchant, so that we can investigate the issue.


Regarding this: 


Have a great day

Best regards 
Allan

**Comment by syntaxerror** [comment]
I see, but in that case it might be better do disable access to the issues completely on each repository here at GitHub (in settings).

And support should probably also respond more quickly, as the client already has talked about giving up Bambora.

Regarding the API user there is no settings to choose when creating those, and the Owner account is added by Bambora. But I'll see if I find anything, in any of those Back Offices available, where we have different access and settings available in all (it's a mess) ... ;)

Thanks. :)
