### ISSUE TITLE
Incompatibility with Woocommerce 2.6

### ISSUE THREAD

**Issue by jbenezech** [bambora/checkout-woocommerce#22]
In ```bambora-online-checkout-helper.php ```, the function ```format_date_time```  has dependencies on these Woocommerce functions: 
- ```wc_string_to_datetime``` and 
- ```wc_format_datetime```

These functions were introduced in Woocommerce version 3.1 and 3.0, respectively. 

The plugin is therefore not compatible with Woocommerce < 3.1.0 although the Readme advertises compatibility with Woocommerce 2.6.

**Comment by AllanWLie** [comment]
Hi @jbenezech 

Thank you for pointing this bug out. We will work on a solution.

If you already have a solution your are welcome to do a Pull request with the changes.

Thank you and have a great weekend.

Best regards 
Allan - Bambora

**Comment by AllanWLie** [comment]
@jbenezech 

Total forgot to inform you that we fixed the issue. It is solved in the latest release
https://github.com/bambora/checkout-woocommerce/releases/latest

-Allan

**Comment by jbenezech** [comment]
Perfect, thanks a lot
