### ISSUE TITLE
Could not load the payment types – Error

### ISSUE THREAD

**Issue by dezzyboy** [bambora/checkout-woocommerce#23]
hey guys i attempted to utilize the plugin as a checkout for our woo-commerce online store and i got the above error code "Could not load the payment types – Error" in the settings i have used our bambora api key for both access token and secret token i think this is where the issue is but unfortunately on the bambora admin dashboard it only has an option to obtain an api key there is no secret key present or a button to  generate one .... any help is greatly appreciated thanks

**Comment by AllanWLie** [comment]
Hi @dezzyboy 

Our plugin requires you to have the "Merchant number", "Access token" and "Secret token" When you create an API user the "Secret token" is only visible once and if you do not have it any more then you will have to generate a new API user in the Bambora administration.

For more support related to this, please contact support@bambora.com and give them your information. 

Best regards
Allan

**Comment by dezzyboy** [comment]
Update This plugin does not support Canadian Merchants that was the issue

**Comment by rajeshwar2** [comment]
any resolution for canadian mechant?

**Comment by sessan** [comment]
Bambora Online does not serve the Canadian Market @rajeshwar2 unfortunately.
