### ISSUE TITLE
Support for Sequential Order Numbers and Sequential Order Numbers Pro

### ISSUE THREAD

**Issue by Razko90** [bambora/checkout-woocommerce#26]
Hi! 

We have a problem with all our orders getting canceled, and we use Sequential Order Numbers Pro.
So when the plugin are trying to load the orders to complete them after a successful purchase we get an error message:

`$message = sprintf( __( 'Could not load the order with order id %s', 'bambora-online-checkout'), $order_id );`

These are regulary used plugins in Norway since since accounting demands sequential order numbers (that Woo dont support out of the box)

I suggest changing out those: https://github.com/bambora/checkout-woocommerce/blob/d0e3202aa4dbd70028189e19d051302d73d8efeb/bambora-online-checkout/bambora-online-checkout.php#L1052 for something like this:

```php
public function bambora_get_real_order($order_id){
	
	if ( class_exists( 'WC_Seq_Order_Number' ) ) {
		global $wc_seq_order_number;
		$order = $wc_seq_order_number->find_order_by_order_number( $order_id );

	} elseif ( class_exists( 'WC_Seq_Order_Number_Pro' ) ) {
		$order = wc_seq_order_number_pro()->find_order_by_order_number( $order_id );
	}else{
		$order = wc_get_order( $order_id );
	}

	return $order;

}

```

**Comment by AllanWLie** [comment]
Hi @Razko90 

Thank you for reporting this feature request. 
I have added it to our backlog for future improvement of the module.

Have a good day.

Best regards
Allan Lie - Bambora Online

**Comment by sessan** [comment]
@Razko90 Hi! We have tested this with the latest version of our plugin and a few different sequential order number-plugins that do work. Could you confirm that this works for you now?

Best Regards

Jessica Björkäng - Bambora Online
