### ISSUE TITLE
Updating / Upgrading routines

### ISSUE THREAD

**Issue by syntaxerror** [bambora/checkout-woocommerce#27]
I wonder about the notice added to releases here on GitHub where it's stated:
`When upgrading to this version, then please remove the old Bambora module. Your old settings will be added to this module when you install it.`

Why is this, and if there is any specific reason for it, would it be possible to do it better?

What's the issues caused by not following this?

I'm asking because most users will never see this notice, as they just see there's a new version in their admin panel. And since most, if not all, other plugins is supposed to be just updated by a click here, they will do the same with Bambora Checkout.

**Comment by AllanWLie** [comment]
Hi @syntaxerror 

it have been removed

Best regards
Allan - Bambora Online A/S
