### ISSUE TITLE
Abandoned carts and cancelled orders

### ISSUE THREAD

**Issue by metuza** [bambora/checkout-woocommerce#28]
After we started to use Bambora we have noticed an increase in abandoned carts and cancelled orders. After weeks of testing and a few phone calls from customers we have found that problems can arrive if a customer has ie. incuffient funds in their vipps account and then go for paying with card or invoice, then it seems like some sessions is conflicting and user get a message that there was a problem with payment. In wp-admin we then find the order registered as awaiting payment and with message that order ID not found in Bambora.

Further testing and when checking transactions errors with Bambora they found that amount was not correct the same as registered with bambora and order was cancelled or not going through.

If a customer get into all these issues and then empty their cart and start the purchase process over again everything works OK. But going further using the first added cart will not work and order is registered pending payment or cancelled.

**Comment by AllanWLie** [comment]
Hi @metuza 

Please contact support@bambora.com

Best regards
Allan - Bambora Online A/S

**Comment by syntaxerror** [comment]
Hi @metuza

Did you ever figure out of this?
Do/Did you use decimals or not?
Is/Did it happening to all payment options, or only one (like Walley (Collector))?

Are getting something similar for Walley at least, where it's stated:
«Invoice total amount is incorrect ePayCollectorBank 2006»
