### ISSUE TITLE
Unessesary API calls, on ALL request.

### ISSUE THREAD

**Issue by jespervnielsen** [bambora/checkout-woocommerce#29]
The plugin is calling https://merchant-v1.api-eu.bambora.com on all requests.. 
Including non-checkout pages, fx a product page.

![image](https://user-images.githubusercontent.com/31649178/123232263-42e18600-d4d9-11eb-8f28-35a004563a29.png)

In bambora-online-checkout.php "set_bambora_description_for_checkout" is being called on construct.
That calls "get_payment_types"  in order to know available payment types..

But is this nessesary to do on all request?
Would'nt it only be required on the actual checkout page, for "set_bambora_description_for_checkout" to run?

As you can see in the screenshot, it adds 200ms loadtime, just to view a product page.

**Comment by sessan** [comment]
This is now fixed in the latest release: 4.6.1.
Thank you for noticing this issue!
Best Regards
Jessica, Bambora Online
