### ISSUE TITLE
E_NOTICE caused by not handling new config fields introduced by upgrading the plugin

### ISSUE THREAD

**Issue by elsand** [bambora/checkout-woocommerce#3]
`init_settings()` does not handle new fields introduced by upgrading the plugin correctly. If any settings at all exists, `$this->settings` are populated with those only - not taking into account any new fields introduced by `init_form_fields()` and attempted accessed in the constructor, and will throw an E_NOTICE. woocommerce_settings_api_form_fields_\* filters are also not taken into account if settings already exists. The fix would be to always call `get_form_fields()` in `ini_settings()` and merge in any already existing settings.

**Comment by AllanWLie** [comment]
Thank you for reporting this issue. We will look into it and consider it for the next release. In the meantime feel free to make a pull request and implement the issues.

**Comment by AllanWLie** [comment]
@elsand 

This is changed in the newest release
