### ISSUE TITLE
Error log - PHP Warning: A non-numeric value encountered

### ISSUE THREAD

**Issue by syntaxerror** [bambora/checkout-woocommerce#30]
I haven't investigated the reason, but several sites have started to log php errors from the Bambora plugin, so just want to give you a heads up on something that probably should be checked.

> PHP Warning:  A non-numeric value encountered in /public_html/wp-content/plugins/bambora-online-checkout/lib/bambora-online-checkout-currency.php on line 46

Bambora Online Checkout 4.6.1
Rounding mode: Default

WooCommerce 5.5.2
Currency: NOK
Currency position: Left with space
Thousand separator: . (dot)
Decimal separator: , (comma)
Number of decimals: 2

**Comment by syntaxerror** [comment]
Just checked one site and the error logging started the same day as updating to Bambora Online Checkout 4.6.1 and WooCommerce 5.5.1

So the compatibility for those and later versions probably needs a closer check asap.

**Comment by sessan** [comment]
A check for empty string is now added ( not only isset) Might be enough to fix this. Please let us know if the problem still persists.

**Comment by syntaxerror** [comment]
Thanks, as fare as I can see this seems solved after updating to latest version of Bambora, so I'll close it for now.
