### ISSUE TITLE
Wrong value returned for $shipping_orderline->unitpricevatamount

### ISSUE THREAD

**Issue by syntaxerror** [bambora/checkout-woocommerce#33]
Ref: https://github.com/bambora/checkout-woocommerce/blob/a3e94db27e5e98743dc40bf9a3a0222ac349414f/bambora-online-checkout/bambora-online-checkout.php#L839

Why not just reuse $shipping_orderline->totalpricevatamount for $shipping_orderline->unitpricevatamount ?

And also reuse $shipping_orderline->totalpriceinclvat for $shipping_orderline->unitpriceinclvat ?
https://github.com/bambora/checkout-woocommerce/blob/master/bambora-online-checkout/bambora-online-checkout.php#L837

Also note the wrong percent value returned on $shipping_orderline->vat ...
https://github.com/bambora/checkout-woocommerce/blob/master/bambora-online-checkout/bambora-online-checkout.php#L840

![Image_2023-02-03_10-34-49](https://user-images.githubusercontent.com/858132/216579625-abddfb2d-5c3b-4e94-a19d-ba4f8cd9b025.png)

**Comment by syntaxerror** [comment]
There is a lot of stores where the customers have problems paying through Walley, and they had it for quite some time, because of the ignorance at Worline's Support, who didn't acknowledge the issue being in your payment plugin.

Seeing all the failed payments regarding Walley should have made some bells ringing both at Worline and Walley long time ago.

Isn't it time to get it sorted, releasing a fix for it?

Just my 5 cents ...

**Comment by sessan** [comment]
Thanks for the feedback.
/Jessica, Bambora Online
