### ISSUE TITLE
Bambora issue

### ISSUE THREAD

**Issue by SyedShoaib06** [bambora/checkout-woocommerce#36]
Pay using Bambora Online Checkout – Could not load the payment types – Error

**Comment by SyedShoaib06** [comment]
i tried every think

**Comment by SyedShoaib06** [comment]
please help me

**Comment by AllanWLie** [comment]
Hi @SyedShoaib06 
It is properly related to wrong access credentials in the configuration section of the module. 

Please reach out to support@bambora.com and they will help you with the correct credentials. 

Best regards
Bambora Online
