### ISSUE TITLE
Fatal error after updating to version 5.1.0

### ISSUE THREAD

**Issue by anders-i** [bambora/checkout-woocommerce#37]
Getting this error message:

Fatal error: Uncaught Exception: Ugyldig ordre. in /var/www/stofmoellen.dk/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:120 Stack trace: #0 /var/www/stofmoellen.dk/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order)) #1 /var/www/stofmoellen.dk/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(128): WC_Data_Store->read(Object(WC_Order)) #2 /var/www/stofmoellen.dk/public_html/wp-content/plugins/bambora-online-checkout/bambora-online-checkout.php(1403): WC_Abstract_Order->__construct(106835) #3 /var/www/stofmoellen.dk/public_html/wp-includes/class-wp-hook.php(310): Bambora_Online_Checkout->bambora_online_checkout_meta_boxes('product') #4 /var/www/stofmoellen.dk/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #5 /var/www/stofmoellen.dk/public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #6 /var/www/stof in /var/www/stofmoellen.dk/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 120

It happens when I try to edit a product on the website can you fix that or is it safe to rollback to older version 5.0.2?

It is on www.stofmoellen.dk

**Comment by sessan** [comment]
@anders-i It is absolutely safe to rollback to the 5.0.2 version. I will however fix this a.s.a.p!

**Comment by sessan** [comment]
@anders-i You can now upgrade to 5.1.1 that fixes this error. 
Best Regards
Jessica Bjorkang, Bambora Online.
