### ISSUE TITLE
critical error woocommerce bambora

### ISSUE THREAD

**Issue by draczilla** [bambora/checkout-woocommerce#38]
[](url)
![image](https://user-images.githubusercontent.com/16039309/234005203-98aa13e4-d61c-4dbe-9bd5-4d5daa7a2c61.png)
whats causing this? something at checkout causes woocommerce to not update the product stock and then when you manually try to correct it it gives critical error

**Comment by sessan** [comment]
What version are you using? Latest? (Was an issue in previous version)

**Comment by draczilla** [comment]
Hi. We are using the latest version 👍

**Comment by syntaxerror** [comment]
Just want to note that your error log is from 16-Mar-2022, **that's more than a year ago**, and the latest version is just 3 weeks old ... ;)

Do you actually have any such error now, with the latest version @draczilla? And if so, what's the rest of your system info including PHP version and server setup?
