### ISSUE TITLE
Uncaught ArgumentCountError: 3 arguments are required, 2 given

### ISSUE THREAD

**Issue by webmasterkinorevuen** [bambora/checkout-woocommerce#39]
We have a recurring error message. The payments are processed , but something is not working right.

Here is an example:
/(...)/wp-content/plugins/bambora-online-classic/bambora-online-classic.php. Fejlbesked: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /(...)/wp-content/plugins/bambora-online-classic/bambora-online-classic.php:1057
Stack trace:
#0 /(...)/wp-content/plugins/bambora-online-classic/bambora-online-classic.php(1057): sprintf('H\xC3\xA6vning af bet...', 9396)
#1 /(...)/wp-content/plugins/bambora-online-classic/bambora-online-classic.php(387): Bambora_Online_Classic->bambora_online_classic_capture_payment(9396, '290.00', 'DKK')
#2 /(...)/wp-includes/class-wp-hook.php(310): Bambora_Online_Classic->bambora_online_classic_order_status_completed(9396)

What can be going on here?

Versions:
Wordpress: 6.2.2
WooCommerce: 7.7.0
PHP: 8.1.19

**Comment by sessan** [comment]
Ok! This was an issue for Classic (you were commenting in the checkout repo)*
This is now fixed in  5.5.1 (it was an issue in the language file)

Best Regards
Jessica Björkäng, Bambora
