### ISSUE TITLE
E_NOTICE caused by calling wp_enqueue_style() / wp_enqueue_script() too early

### ISSUE THREAD

**Issue by elsand** [bambora/checkout-woocommerce#4]
The plugin is set up to enqueue styles and scripts in the 'plugins_loaded' action, which is deprecated in Wordpress and throws a warning in Wordpress 3.3+. This can be fixed by adding an 'wp_enqueue_scripts' action handler, and call `wp_enqueue_style()` / `wp_enqueue_script()`

**Comment by AllanWLie** [comment]
Thank you for reporting this issue. We will look into it and consider it for the next release. In the meantime feel free to make a pull request and implement the issues.

**Comment by sorenla** [comment]
Fixed in version 1.2.8
