### ISSUE TITLE
Issue with Wordpress get_locale() and finnish language 'fi' instead of 'fi_FI'.

### ISSUE THREAD

**Issue by KalleMus** [bambora/checkout-woocommerce#40]
Hello bambora devs,

I have a finnish woocommerce wordpress website and when I try to do a checkout, I receive this error message:
_"Could not retrive the payment window. Reason: The request contained an invalid model. Please try again"_

The issue might be this: 
Since the bambora API requires the language code as `'fi_FI'`, but the Wordpress `get_locale()` function returns `'fi'`.
_https://avada.com/documentation/complete-list-of-wordpress-language-locales/_
_https://developer.bambora.com/europe/checkout/getting-started/checkout-settings#Language_

https://github.com/bambora/checkout-woocommerce/blob/7bcccd878e0b453d86417edd681cb49850d7616a/bambora-online-checkout/bambora-online-checkout.php#L666

My suggestion is that, in these cases, when `get_locale()` returns a string like `'fi'`, it should be converted to `'fi-FI'`, before adding it into the request.

I made a possible fix on my fork, but have not tested it nor created a pull request yet, because I wanted to create an issue about it first.
Commits: https://github.com/KalleMus/checkout-woocommerce/commit/2ad299a46eabd80e519cc9facc644c71363f25e2, https://github.com/KalleMus/checkout-woocommerce/commit/2ea1396e051589f8188281615f893e3105547c61
```
private function get_language() {
  $language = get_locale();
  if ( !str_contains( $language, '_' )) {
    return $language . '-' . strtoupper( $language );
  }
  return str_replace( '_', '-', $language );
}
```

**Comment by syntaxerror** [comment]
That sounds like a language pack issue to me, which shouldn't be fixed in the module, but rather in the language pack - else the issue will show up elsewhere also (other plugins).

Just my 5 cents. ;)

**Comment by sessan** [comment]
This is fixed in the latest release.

Best Regards
Jessica Björkäng, Bambora.
