### ISSUE TITLE
Improve error/events handling

### ISSUE THREAD

**Issue by elsand** [bambora/checkout-woocommerce#5]
Errors/exceptions are usually just written directly to the client with echo without any logging. There should be an centralised handler for all errors, which makes sure any errors are logged the same way as transactions, and allowing for notifications of errors to an e-mail. Preferably an action should be triggered, making it possible to customize event handling (eg. for utilizing logstash or other sentralized logging)

**Comment by AllanWLie** [comment]
Thank you for reporting this issue. We will look into it and consider it for the next release. In the meantime feel free to make a pull request and implement the issues.

**Comment by AllanWLie** [comment]
Hi @elsand 
We have in the newest release added logging to the module. Please notice that the release is a Beta release and it might not be stable. Please make a backup of your shop before installing this version
