### ISSUE TITLE
Inconsistent code style, minor issues

### ISSUE THREAD

**Issue by elsand** [bambora/checkout-woocommerce#7]
There are several minor style issues. Please consider addressing these to improve overall quality:

- All files use a mix of tabs and spaces. This can cause messy diffs, and can cause inconsistent rendering of the code in various editors/viewers, see e.g. https://github.com/bambora/checkout-woocommerce/blob/master/woocommerce-gateway-bambora/woocommerce-gateway-bambora.php

- Several files (not all) includes a closing `?>` as the last token of the file. This is unneccesary and discouraged, as any succeeding whitespace will be written to the response, which may cause hard-to-find bugs. 

- `WC_Gateway_Bambora` sets several properties dynamically in its constructor (`merchant`, `accesstoken`, `secrettoken`etc). Explicitly declaring those properties helps readability, static analysis in IDEs and reduces the chance of typos.

- The `$woocommerce` global is declared, but not used in the constructor and several other methods. 

- `create_bambora_url()` does not use its second (non-optional) parameter.

**Comment by AllanWLie** [comment]
Thank you for reporting this issue. We will look into it and consider it for the next release. In the meantime feel free to make a pull request and implement the feature.

**Comment by sorenla** [comment]
Fixed in version 1.2.8
