### ISSUE TITLE
Implement support for WooCommerce Subscriptions

### ISSUE THREAD

**Issue by elsand** [bambora/checkout-woocommerce#8]
Please consider implementing support for recurring payments as provided by https://www.woothemes.com/products/woocommerce-subscriptions/

**Comment by AllanWLie** [comment]
Thank you for reporting this issue. We will look into it and consider it for the next release. In the meantime feel free to make a pull request and implement the feature.

**Comment by AllanWLie** [comment]
The module now supports recuring payments
