### ISSUE TITLE
Callback does not correctly handle Woocommerce inventory management

### ISSUE THREAD

**Issue by elsand** [bambora/checkout-woocommerce#9]
When inventory management is enabled in Woocommerce, orders set with status "pending payment" are automatically cancelled after 60 minutes (by default) and the held stock is released and made available to others. See http://www.jeriffcheng.com/unpaid-order-cancelled-time-limit-reached.html.

If - due to eg. network issues - the callback takes more than the configured amount of minutes to reach the callback handler, the order does not get updated, but the plugin still returns a 200 status unconditionally.

``` php
    function successful_request($posted)
    {
                // ... snip ...
                if(isset($order) && $order->has_status('pending'))
                {
                    // ... snip ...
                }
                status_header(200);
                // ... snip ...
       }
```

Returning 200, indicating success, when the request effectively has failed due to the has_status('pending') check, is probably not desired behaviour. Perhaps a different code could be returned, indicating that the order has been cancelled, triggering an event log entry and ceasing further callback attempts.

**Comment by AllanWLie** [comment]
@elsand 

This is changed in the newest release
